stages:
  - test
  - update_tests
  - cleanup

# Note: After this first stage has completed, the pipeline will return this error: "WARNING: youtube_invaders_video.png: no matching files. Ensure that the artifact path is relative to the working directory". Ignore this error, as this stage is completing its intended purpose.
simulate_user_activity:
  allow_failure: true
  image:
    name: alpine/helm
    entrypoint: [""]
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  stage: test
  artifacts:
    paths:
      - ${ARTIFACT}
  script:
    - apk add --no-cache python3 py3-pip jq
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
# install the ueransim helm chart, but using the image we build that includes puppeteer and our test scripts
    - >
      COMMON_LABEL=$(jq -n --arg CI_JOB_ID "${CI_JOB_ID}" --arg SCRIPT "${SCRIPT}" '{"gitlab-job": $CI_JOB_ID, "puppeteer-script": $SCRIPT}')
    - > 
      helm -n openverso upgrade --install ueransim-ues-puppeteer-${SCRIPT}  openverso/ueransim-ues \
        --set ues.initialMSISDN="${IMSI_ID}"   \
        --set image.registry=018300759195.dkr.ecr.us-east-1.amazonaws.com --set image.repository=cntf-ueransim-puppeteer \
        --set-json commonLabels="${COMMON_LABEL}" \
        --set-json podLabels="${COMMON_LABEL}" \
        --values https://raw.githubusercontent.com/DISHDevEx/napp/main/napp/open5gs_values/gnb_ues_values.yaml
    - kubectl -n openverso rollout status deployment ueransim-ues-puppeteer-${SCRIPT}
    - kubectl -n openverso exec deployment.apps/ueransim-ues-puppeteer-${SCRIPT} -- bash -c "node /app/${SCRIPT}.js >&1"
    - UE_POD=$(kubectl -n openverso get pod --output=jsonpath={.items..metadata.name} -l gitlab-job=$CI_JOB_ID)
    - kubectl -n openverso cp ${UE_POD}:/app/${ARTIFACT} ./${ARTIFACT}
  parallel:
    matrix:
      - SCRIPT: youtube-search
        IMSI_ID: 9090909090
        ARTIFACT: youtube_invaders_video.png
      # - SCRIPT: amazon-search
      #   IMSI_ID: 9090909091
      #   ARTIFACT: 5g_reference_guide.png        # Currently the amazon-search and dev-tools-search feautures are not working.
      # - SCRIPT: devtools-search
      #   IMSI_ID: 9090909092

update_test_results:
  allow_failure: true
  image:
    name: alpine/helm
    entrypoint: [""]
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  stage: update_tests
  script:
    - apk add --no-cache python3 py3-pip jq
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - pip3 install --no-cache-dir boto3  # Install boto3 library for AWS interaction
    - aws --version
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - python3 ./s3_test_results_coralogix.py # converts over5g.json & overinternet.json files into objects in an S3 bucket
    - sh ./update_test_results.sh
   
puppeteer-cleanup:
  image:
    name: alpine/helm
    entrypoint: [""]
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  needs: 
    - simulate_user_activity
    - update_test_results
  stage: cleanup
  environment:
    name: open5gs_cluster
  script:
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
# remove smoke-test helm release
    - helm -n openverso uninstall ueransim-ues-puppeteer-${SCRIPT}
  parallel:
    matrix:
      - SCRIPT: 
          - youtube-search
          - amazon-search
          - devtools-search
  rules:
    - when: manual
